import { Cat } from './cat';

export const CATEGORIES: Cat[] = [
  { id: 0, name: 'Все категории', class: "" },
  { id: 6014, name: 'Игры', class: "cat-games" },  
  { id: 6001, name: 'Погода', class: "cat-weather" },  
  { id: 6007, name: 'Производительность', class: "cat-prod" },
  { id: 6008, name: 'Фото и видео', class: "cat-photo" },
  { id: 6003, name: 'Путешествия', class: "cat-travel" },
  { id: 6004, name: 'Спорт', class: "cat-sport" },
  { id: 6016, name: 'Развлечения', class: "cat-entertain" },
  { id: 6000, name: 'Бизнес', class: "cat-business" },
  { id: 6002, name: 'Утилиты', class: "cat-utilities" }, 
  //{ id: 6009, name: 'Новости', class: "cat-news" },
  { id: 6010, name: 'Навигация', class: "cat-nav" },
  { id: 6011, name: 'Музыка', class: "cat-music" },  
  { id: 6012, name: 'Образ жизни', class: "cat-lifestyle" },
  { id: 6013, name: 'Здоровье и фитнес', class: "cat-health" },
  { id: 6005, name: 'Социальные сети', class: "cat-social" },  
  { id: 6006, name: 'Справочники', class: "cat-ref" },
  { id: 6015, name: 'Финансы', class: "cat-finance" },  
  { id: 6017, name: 'Образование', class: "cat-edu" },
  { id: 6018, name: 'Книги', class: "cat-books" },
  { id: 6020, name: 'Медицина', class: "cat-medical" },
  { id: 6021, name: 'Киоск', class: "cat-magazine" },
  { id: 6022, name: 'Каталоги', class: "cat-catalogue" },
  { id: 6023, name: 'Еда и напитки', class: "cat-food" },
  { id: 12001, name: 'Бизнес', class: "" },  
  { id: 12002, name: 'Инструменты разработчика', class: "" },
  { id: 12003, name: 'Образование', class: "" },
  { id: 12004, name: 'Развлечения', class: "" },
  { id: 12005, name: 'Финансы', class: "" },
  { id: 12006, name: 'Игры', class: "" },
  { id: 12007, name: 'Здоровье и фитнес', class: "" },
  { id: 12008, name: 'Образ жизни', class: "" },  
  { id: 12010, name: 'Медицина', class: "" },
  { id: 12011, name: 'Музыка', class: "" },
  { id: 12012, name: 'Новости', class: "" },
  { id: 12013, name: 'Фотография', class: "" },
  { id: 12014, name: 'Производительность', class: "" },
  { id: 12015, name: 'Справочники', class: "" },
  { id: 12016, name: 'Социальные сети', class: "" },
  { id: 12017, name: 'Спорт', class: "" },
  { id: 12018, name: 'Путешествия', class: "" },
  { id: 12019, name: 'Утилиты', class: "" },
  { id: 12020, name: 'Видео', class: "" },
  { id: 12021, name: 'Погода', class: "" },
  { id: 12022, name: 'Графика и дизайн', class: "" }];

export const SUBCATEGORIES: Cat[] = [
  { id: 0, name: 'Все категории', class: "" },
  { id:7001,  name:"боевики", class: "" },
  {id:7002, name:"приключения", class: "" },
  {id:7003, name:"аркады", class: "" },
  {id:7004, name:"настольные игры", class: "" },
  {id:7005, name:"карточные игры", class: "" },
  {id:7006, name:"казино", class: "" },
  {id:7007, name:"игры в кости", class: "" },
  {id:7008, name:"обучающие", class: "" },
  {id:7009, name:"семейные", class: "" },
  {id:7010, name:"детские", class: "" },
  {id:7011, name:"музыка", class: "" },
  {id:7012, name:"головоломки", class: "" },
  {id:7013, name:"гоночные игры", class: "" },
  {id:7014, name:"ролевые игры", class: "" },
  {id:7015, name:"симуляторы", class: "" },
  {id:7016, name:"спорт", class: "" },
  {id:7017, name:"стратегии", class: "" },
  {id:7018, name:"любопытные мелочи", class: "" },
  {id:7019, name:"словесные игры", class: "" },
  {id:12201, name:"боевики", class: "" },
  {id:12202, name:"приключения", class: "" },
  {id:12203, name:"аркады", class: "" },
  {id:12204, name:"настольные", class: "" },
  {id:12205, name:"карточные", class: "" },
  {id:12206, name:"казино", class: "" },
  {id:12207, name:"игры в кости", class: "" },
  {id:12208, name:"обучающие игры", class: "" },
  {id:12209, name:"семейные игры", class: "" },
  {id:12210, name:"детские игры", class: "" },
  {id:12211, name:"музыка", class: "" },
  {id:12212, name:"головоломки", class: "" },
  {id:12213, name:"гонки", class: "" },
  {id:12214, name:"ролевые игры", class: "" },
  {id:12215, name:"симуляторы", class: "" },
  {id:12216, name:"спорт", class: "" },
  {id:12217, name:"стратегии", class: "" },
  {id:12218, name:"любопытные мелочи", class: "" },
  {id:12219, name:"словесные игры", class: "" } 
];